apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multiple-apps-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/MatiWall/application-values.git
      revision: master
      directories:
      - path: personal-website
        #helm:
        #  valueFiles:
        #  - values.yaml
      - path: docker-registry
      - path: docker-registry-ui
  template:
    metadata:
      name: '{{ .Parameters.repoName }}-{{ .Parameters.appName }}'
    spec:
      destination:
        namespace: '{{ .Parameters.appName }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
        path: '{{ .Parameters.appName }}'
        repoURL: https://github.com/MatiWall/application-values.git
        targetRevision: HEAD

