apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multiple-apps-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/MatiWall/application-values.git
      revision: master
      directories:
        - path: docker-registry
      values:
        namespace: docker-registry
        name: docker-registry
        helm: false
  - git:
      repoURL: https://github.com/MatiWall/application-values.git
      revision: master
      directories:
        - path: personal-website
      values:
        namespace: mw
        name: personal-website
        helm: true
  template:
    metadata:
      name: '{{ values.name }}'
    spec:
      destination:
        namespace: '{{ values.namespace }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        {{- if values.helm }}
        helm:
          valueFiles:
            - values.yaml
        {{- else }}
        path: '{{ .path.path }}'
        repoURL: https://github.com/MatiWall/application-values.git
        targetRevision: HEAD
        {{- end }}

