apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-tools-heml-apps-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/MatiWall/homelab.cluster-tools.application-values.git
      revision: main
      directories:
        - path: grafana-dashboards
      values:
        namespace: grafana
  - git:
      repoURL: https://github.com/MatiWall/homelab.cluster-tools.application-values.git
      revision: main
      directories:
        - path: vault-injector
      values:
        namespace: vault
  - git:
      repoURL: https://github.com/MatiWall/homelab.cluster-tools.application-values.git
      revision: main
      directories:
        - path: argo/workflow/argo-workflow
      values:
        namespace: argo
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      destination:
        namespace: '{{ values.namespace }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/MatiWall/homelab.cluster-tools.application-values.git
        helm:
          valueFiles:
            - values.yaml
        path: '{{ path }}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

