apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multiple-apps-set
  namespace: argocd
spec:
  generators:
  - git:
      revision: master
      directories:
        repoURL: https://github.com/MatiWall/application-values.git
        - path: personal-website
      values:
        namespace: mw
        name: personal-website
        helm: true
  template:
    metadata:
      name: '{{ values.name }}'
    spec:
      destination:
        namespace: '{{ values.namespace }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        path: '{{ path }}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

